In [2]:
#CALL IN DATASET

In [3]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import warnings

#Read in the data

In [4]:
df_Group1 = pd.read_csv('FOOD-DATA-GROUP1.csv')
df_Group1.head()

,Unnamed: 0.1,Unnamed: 0,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
0,0,0,cream cheese,51,5.0,2.9,1.3,0.200,0.8,0.500,...,0.008,14.100,0.082,0.027,1.300,0.091,15.5,19.100,0.039,7.070
1,1,1,neufchatel cheese,215,19.4,10.9,4.9,0.800,3.1,2.700,...,99.500,0.034,0.100,8.500,0.088,117.300,129.2,0.054,0.700,130.100
2,2,2,requeijao cremoso light catupiry,49,3.6,2.3,0.9,0.000,0.9,3.400,...,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,5.400
3,3,3,ricotta cheese,30,2.0,1.3,0.5,0.002,1.5,0.091,...,0.097,41.200,0.097,0.096,4.000,0.024,30.8,43.800,0.035,5.196
4,4,4,cream cheese low fat,30,2.3,1.4,0.6,0.042,1.2,0.900,...,22.200,0.072,0.008,1.200,0.098,22.800,37.1,0.034,0.053,27.007

In [6]:
df_Group2 = pd.read_csv('FOOD-DATA-GROUP2.csv')
df_Group2.head()

,Unnamed: 0.1,Unnamed: 0,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
0,0,0,eggnog,224,10.6,6.6,3.3,0.5,20.4,20.4,...,330.2,0.051,0.500,48.3,0.024,276.9,419.1,0.094,1.200,377.200
1,1,1,beer light,96,0.0,0.0,0.0,0.0,5.4,0.3,...,13.2,0.095,0.014,16.5,0.094,39.6,69.3,0.077,0.044,19.456
2,2,2,beer budweiser,12,0.0,0.0,0.0,0.0,0.9,0.0,...,1.2,0.095,0.000,2.1,0.038,3.8,9.7,0.000,0.000,2.200
3,3,3,weizenbier erdinger,220,18.0,13.0,1.0,0.0,0.0,0.0,...,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.000,0.000,18.000
4,4,4,beer light budweiser,9,0.0,0.0,0.0,0.0,0.4,0.0,...,0.9,0.088,0.000,2.1,0.007,3.2,7.7,0.000,0.000,1.320

In [7]:
df_Group3 = pd.read_csv('FOOD-DATA-GROUP3.csv')
df_Group3.head()

,Unnamed: 0.1,Unnamed: 0,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
0,0,0,nectarine,66,0.500,0.066,0.100,0.200,15.8,11.8,...,0.081,9.000,0.100,0.4,13.500,0.002,39.0,301.500,0.000,20.735
1,1,1,kiwifruit gold,51,0.200,0.008,0.099,0.051,12.8,10.0,...,13.800,0.100,0.200,9.7,0.072,20.300,255.2,0.003,0.077,159.686
2,2,2,prickly pear raw,8,0.072,0.000,0.000,0.000,1.9,0.2,...,34.200,0.051,0.021,13.1,0.100,2.100,24.7,0.023,0.073,39.263
3,3,3,pineapple,45,0.100,0.074,0.001,0.087,11.8,8.9,...,0.061,11.700,0.091,0.3,10.800,0.800,7.2,98.100,0.061,13.970
4,4,4,rowan,253,4.600,0.600,0.000,0.000,54.5,32.1,...,34.200,2.400,5.000,73.0,0.400,118.600,298.7,0.000,1.000,176.400

In [8]:
df_Group4 = pd.read_csv('FOOD-DATA-GROUP4.csv')
df_Group4.head()

,Unnamed: 0.1,Unnamed: 0,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
0,0,0,chocolate pudding fat free,105,0.3,0.0,0.00,0.000,23.6,17.8,...,44.100,0.035,1.900,17.0,0.040,61.0,235.0,0.052,0.300,72.400
1,1,1,tapioca pudding,143,4.3,1.1,2.80,0.088,23.9,16.4,...,78.100,0.026,0.100,6.6,0.096,66.0,101.2,0.000,0.200,108.800
2,2,2,tapioca pudding fat free,105,0.4,0.1,0.08,0.067,23.9,15.9,...,58.200,0.004,0.100,5.6,0.023,73.9,78.4,0.000,0.200,84.500
3,3,3,rice pudding,122,2.4,1.4,0.60,0.100,20.8,13.1,...,0.063,107.400,0.014,0.1,9.000,0.1,92.7,141.300,0.083,27.329
4,4,4,corn pudding,328,12.6,6.3,3.90,1.400,42.4,16.5,...,0.066,97.500,0.100,1.3,37.500,0.2,225.0,440.000,0.069,69.795

In [9]:
df_Group5 = pd.read_csv('FOOD-DATA-GROUP5.csv')
df_Group5.head()

,Unnamed: 0.1,Unnamed: 0,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
0,0,0,margarine with yoghurt,88,9.8,1.9,5.6,2.0,0.073,0.0,...,2.8,0.001,0.027,0.3,0.0,2.2,3.5,0.000,0.008,12.971
1,1,1,sunflower seed butter,99,8.8,0.7,6.2,1.6,3.700,1.7,...,10.2,0.300,0.700,49.8,0.3,106.6,92.2,0.075,0.800,27.500
2,2,2,hazelnut oil,120,13.6,1.0,10.6,1.4,0.000,0.0,...,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.000,0.000,13.600
3,3,3,menhaden fish oil,1966,218.0,66.3,58.2,74.5,0.000,0.0,...,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.000,0.000,218.000
4,4,4,cod liver fish oil,123,13.6,3.1,6.4,3.1,0.000,0.0,...,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.000,0.000,17.700

In [10]:
df_Grouped_combined= pd.concat([df_Group1,df_Group2,df_Group3,df_Group4,df_Group5])
df_Grouped_combined

,Unnamed: 0.1,Unnamed: 0,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
0,0,0,cream cheese,51,5.000,2.900,1.300,0.200,0.8,0.500,...,0.008,14.100,0.082,0.027,1.300,0.091,15.5,19.100,0.039,7.070
1,1,1,neufchatel cheese,215,19.400,10.900,4.900,0.800,3.1,2.700,...,99.500,0.034,0.100,8.500,0.088,117.300,129.2,0.054,0.700,130.100
2,2,2,requeijao cremoso light catupiry,49,3.600,2.300,0.900,0.000,0.9,3.400,...,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,5.400
3,3,3,ricotta cheese,30,2.000,1.300,0.500,0.002,1.5,0.091,...,0.097,41.200,0.097,0.096,4.000,0.024,30.8,43.800,0.035,5.196
4,4,4,cream cheese low fat,30,2.300,1.400,0.600,0.042,1.2,0.900,...,22.200,0.072,0.008,1.200,0.098,22.800,37.1,0.034,0.053,27.007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
717,717,717,jews ear,25,0.095,0.000,0.000,0.000,6.7,0.000,...,15.800,0.400,0.600,24.800,0.040,13.900,42.6,0.034,0.700,24.249
718,718,718,enoki mushrooms,1,0.099,0.027,0.000,0.010,0.2,0.034,...,0.000,0.000,0.099,0.034,0.500,0.015,3.2,10.800,0.096,0.433
719,719,719,morel mushrooms,4,0.070,0.056,0.031,0.007,0.7,0.096,...,0.000,5.500,0.056,1.600,2.500,0.060,25.0,53.000,0.069,1.727
720,720,720,portabella mushrooms raw,19,0.300,0.036,0.016,0.100,3.3,2.200,...,2.600,0.200,0.300,0.000,0.092,92.900,313.0,0.015,0.500,9.400
721,721,721,oyster mushroom,5,0.035,0.016,0.039,0.099,0.9,0.200,...,0.000,0.500,0.008,0.200,2.700,0.055,18.0,63.000,0.048,1.804